name: Continuous Integration & Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyse:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check "./**/*.{json,yml}"

  build:
    needs: [ analyse ]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository }}
          tag-sha: true
          tag-custom: latest
      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
